version: '3.1'
services:
  db:
    user: $UID
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: auth
      MONGO_USERNAME: vish
      MONGO_PASSWORD: Comnet123
    volumes:
      - ./data1:/data/db 
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    restart: always
  
  cache:
    image: redis:alpine
    ports:
     - '6379:6379'
    command: ['--requirepass "secret"']